version: 0.2
phases:
  install:
    # Refer to the install buildspec file
    - source: buildspec_install.yaml
  pre_build:
    # Refer to the SonarQube analysis buildspec file
    - source: buildspec_sonar.yaml
    - source: buildspec_trivy.yaml
  build:
    # Refer to the build phase (React app build)
    - source: buildspec_build.yaml
  post_build:
    commands:
      - echo All phases completed successfully.
