version: 0.2
phases:
  install:
    commands:
      - echo Installing Trivy...
      - curl -sfL https://github.com/aquasecurity/trivy/releases/download/v0.29.0/trivy_0.29.0_Linux-64bit.tar.gz | tar -xzv
  build:
    commands:
      - echo Running Trivy security scan on the source code...
      - ./trivy fs --severity HIGH,MEDIUM --no-progress --ignore-unfixed --exclude node_modules,dist,public .
  post_build:
    commands:
      - echo Trivy scan completed.

artifacts:
  files:
    - '**/*'
