version: 0.2
phases:
  install:
    commands:
      - echo Installing Trivy...
      - curl -sfL https://github.com/aquasecurity/trivy/releases/download/v0.29.0/trivy_0.29.0_Linux-64bit.tar.gz | tar -xzv
  build:
    commands:
      - echo Running Trivy security scan...
      # - ./trivy fs --exit-code 1 --severity HIGH,CRITICAL --no-progress .
      - ./trivy fs --exit-code 1 --severity HIGH,CRITICAL --no-progress .
  post_build:
    commands:
      - echo Trivy scan completed.

artifacts:
  files:
    - '**/*'